"""
Exercise Library - Comprehensive exercise database for Home and Gym environments.
Each exercise includes: name, category, role, muscle group, sets/reps, video mapping.
Categorized by: Push / Pull / Legs / Core / Conditioning
"""

EXERCISES = {
    "home": {
        "push": [
            {
                "id": "push_ups",
                "name": "Push-Ups",
                "category": "push",
                "role": "primary",
                "muscle_group": "Chest, Shoulders, Triceps",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "IODxDxX7oi4",
                "description": "Standard push-up with proper form",
                "difficulty": "beginner"
            },
            {
                "id": "diamond_push_ups",
                "name": "Diamond Push-Ups",
                "category": "push",
                "role": "primary",
                "muscle_group": "Triceps, Inner Chest",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 60,
                "video_id": "J0DnG1_S92I",
                "description": "Close-grip push-up targeting triceps",
                "difficulty": "intermediate"
            },
            {
                "id": "pike_push_ups",
                "name": "Pike Push-Ups",
                "category": "push",
                "role": "primary",
                "muscle_group": "Shoulders, Triceps",
                "sets": 3,
                "reps": "8-12",
                "rest_seconds": 60,
                "video_id": "sposDXWEB0A",
                "description": "Shoulder-focused push-up variation",
                "difficulty": "intermediate"
            },
            {
                "id": "decline_push_ups",
                "name": "Decline Push-Ups",
                "category": "push",
                "role": "accessory",
                "muscle_group": "Upper Chest, Shoulders",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 60,
                "video_id": "SKPab2YC8BE",
                "description": "Elevated feet push-up for upper chest emphasis",
                "difficulty": "intermediate"
            },
            {
                "id": "wide_push_ups",
                "name": "Wide Push-Ups",
                "category": "push",
                "role": "accessory",
                "muscle_group": "Chest, Shoulders",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "pfMvAJgpmrY",
                "description": "Wide-grip push-up emphasizing chest stretch",
                "difficulty": "beginner"
            },
        ],
        "pull": [
            {
                "id": "resistance_band_rows",
                "name": "Resistance Band Rows",
                "category": "pull",
                "role": "primary",
                "muscle_group": "Back, Biceps",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "RVwVAzoDBJE",
                "description": "Seated row using resistance band",
                "difficulty": "beginner"
            },
            {
                "id": "superman_holds",
                "name": "Superman Holds",
                "category": "pull",
                "role": "primary",
                "muscle_group": "Lower Back, Glutes",
                "sets": 3,
                "reps": "15-20",
                "rest_seconds": 45,
                "video_id": "z6PJMT2y8GQ",
                "description": "Prone back extension hold",
                "difficulty": "beginner"
            },
            {
                "id": "doorway_rows",
                "name": "Doorway Rows",
                "category": "pull",
                "role": "primary",
                "muscle_group": "Back, Biceps",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 60,
                "video_id": "LR2EnFWpVao",
                "description": "Bodyweight row using a doorframe",
                "difficulty": "beginner"
            },
            {
                "id": "reverse_snow_angels",
                "name": "Reverse Snow Angels",
                "category": "pull",
                "role": "accessory",
                "muscle_group": "Upper Back, Rear Delts",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 45,
                "video_id": "0aqkMC1eZbk",
                "description": "Prone arm sweep for upper back activation",
                "difficulty": "beginner"
            },
            {
                "id": "towel_curls",
                "name": "Towel Bicep Curls",
                "category": "pull",
                "role": "accessory",
                "muscle_group": "Biceps",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 45,
                "video_id": "TCLXSO5JvX0",
                "description": "Isometric bicep curl using a towel",
                "difficulty": "beginner"
            },
        ],
        "legs": [
            {
                "id": "bodyweight_squats",
                "name": "Bodyweight Squats",
                "category": "legs",
                "role": "primary",
                "muscle_group": "Quads, Glutes, Hamstrings",
                "sets": 3,
                "reps": "15-20",
                "rest_seconds": 60,
                "video_id": "aclHkVaku9U",
                "description": "Standard bodyweight squat with full range",
                "difficulty": "beginner"
            },
            {
                "id": "lunges",
                "name": "Walking Lunges",
                "category": "legs",
                "role": "primary",
                "muscle_group": "Quads, Glutes, Hamstrings",
                "sets": 3,
                "reps": "12 each leg",
                "rest_seconds": 60,
                "video_id": "QOVaHwm-Q6U",
                "description": "Alternating forward lunges",
                "difficulty": "beginner"
            },
            {
                "id": "bulgarian_split_squat",
                "name": "Bulgarian Split Squats",
                "category": "legs",
                "role": "primary",
                "muscle_group": "Quads, Glutes",
                "sets": 3,
                "reps": "10 each leg",
                "rest_seconds": 60,
                "video_id": "2C-uNgKwPLE",
                "description": "Single-leg squat with rear foot elevated",
                "difficulty": "intermediate"
            },
            {
                "id": "wall_sit",
                "name": "Wall Sit",
                "category": "legs",
                "role": "accessory",
                "muscle_group": "Quads, Glutes",
                "sets": 3,
                "reps": "30-45 sec hold",
                "rest_seconds": 45,
                "video_id": "y-wV4Lz6pKk",
                "description": "Isometric squat hold against wall",
                "difficulty": "beginner"
            },
            {
                "id": "calf_raises_home",
                "name": "Calf Raises",
                "category": "legs",
                "role": "accessory",
                "muscle_group": "Calves",
                "sets": 3,
                "reps": "20-25",
                "rest_seconds": 30,
                "video_id": "gwLzBJYoWlI",
                "description": "Standing calf raise on elevated surface",
                "difficulty": "beginner"
            },
        ],
        "core": [
            {
                "id": "plank",
                "name": "Plank Hold",
                "category": "core",
                "role": "primary",
                "muscle_group": "Core, Shoulders",
                "sets": 3,
                "reps": "30-60 sec hold",
                "rest_seconds": 45,
                "video_id": "ASdvN_XEl_c",
                "description": "Front plank with proper alignment",
                "difficulty": "beginner"
            },
            {
                "id": "mountain_climbers",
                "name": "Mountain Climbers",
                "category": "core",
                "role": "primary",
                "muscle_group": "Core, Hip Flexors, Shoulders",
                "sets": 3,
                "reps": "20 each side",
                "rest_seconds": 45,
                "video_id": "nmwgirgXLYM",
                "description": "Dynamic plank with alternating knee drives",
                "difficulty": "beginner"
            },
            {
                "id": "bicycle_crunches",
                "name": "Bicycle Crunches",
                "category": "core",
                "role": "primary",
                "muscle_group": "Obliques, Rectus Abdominis",
                "sets": 3,
                "reps": "15 each side",
                "rest_seconds": 45,
                "video_id": "9FGilxCbdz8",
                "description": "Rotational crunch targeting obliques",
                "difficulty": "beginner"
            },
            {
                "id": "leg_raises",
                "name": "Lying Leg Raises",
                "category": "core",
                "role": "accessory",
                "muscle_group": "Lower Abs, Hip Flexors",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 45,
                "video_id": "JB2oyawG9KI",
                "description": "Supine leg raise for lower abs",
                "difficulty": "intermediate"
            },
            {
                "id": "dead_bugs",
                "name": "Dead Bugs",
                "category": "core",
                "role": "accessory",
                "muscle_group": "Deep Core, Stabilizers",
                "sets": 3,
                "reps": "10 each side",
                "rest_seconds": 45,
                "video_id": "4XLEnwUr1d8",
                "description": "Anti-extension core stability exercise",
                "difficulty": "beginner"
            },
        ],
        "conditioning": [
            {
                "id": "burpees",
                "name": "Burpees",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Full Body",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 60,
                "video_id": "dZgVxmf6jkA",
                "description": "Full body explosive conditioning move",
                "difficulty": "intermediate"
            },
            {
                "id": "high_knees",
                "name": "High Knees",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Hip Flexors, Core, Cardio",
                "sets": 3,
                "reps": "30 sec",
                "rest_seconds": 30,
                "video_id": "tx5rgpDAJRI",
                "description": "Running in place with high knee drive",
                "difficulty": "beginner"
            },
            {
                "id": "jumping_jacks",
                "name": "Jumping Jacks",
                "category": "conditioning",
                "role": "accessory",
                "muscle_group": "Full Body, Cardio",
                "sets": 3,
                "reps": "30 sec",
                "rest_seconds": 30,
                "video_id": "c4DAnQ6DtF8",
                "description": "Classic cardio warm-up exercise",
                "difficulty": "beginner"
            },
            {
                "id": "shadow_boxing",
                "name": "Shadow Boxing",
                "category": "conditioning",
                "role": "accessory",
                "muscle_group": "Shoulders, Core, Cardio",
                "sets": 3,
                "reps": "60 sec",
                "rest_seconds": 30,
                "video_id": "ZRrVIbFBL9U",
                "description": "Controlled punch combinations in air",
                "difficulty": "beginner"
            },
            {
                "id": "jump_squats",
                "name": "Jump Squats",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Quads, Glutes, Cardio",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 60,
                "video_id": "A-cFYGvaXc4",
                "description": "Explosive squat with vertical jump",
                "difficulty": "intermediate"
            },
        ],
    },
    "gym": {
        "push": [
            {
                "id": "bench_press",
                "name": "Barbell Bench Press",
                "category": "push",
                "role": "primary",
                "muscle_group": "Chest, Shoulders, Triceps",
                "sets": 4,
                "reps": "8-10",
                "rest_seconds": 90,
                "video_id": "rT7DgCr-3pg",
                "description": "Flat barbell bench press - king of push exercises",
                "difficulty": "intermediate"
            },
            {
                "id": "overhead_press",
                "name": "Overhead Press",
                "category": "push",
                "role": "primary",
                "muscle_group": "Shoulders, Triceps",
                "sets": 4,
                "reps": "8-10",
                "rest_seconds": 90,
                "video_id": "2yjwXTZQDDI",
                "description": "Standing barbell shoulder press",
                "difficulty": "intermediate"
            },
            {
                "id": "incline_db_press",
                "name": "Incline Dumbbell Press",
                "category": "push",
                "role": "primary",
                "muscle_group": "Upper Chest, Shoulders",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 75,
                "video_id": "8iPEnn-ltC8",
                "description": "Incline press with dumbbells for upper chest",
                "difficulty": "intermediate"
            },
            {
                "id": "cable_flyes",
                "name": "Cable Flyes",
                "category": "push",
                "role": "accessory",
                "muscle_group": "Chest",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "Iwe6AmxVf7o",
                "description": "Cable crossover for chest isolation",
                "difficulty": "beginner"
            },
            {
                "id": "tricep_pushdowns",
                "name": "Tricep Pushdowns",
                "category": "push",
                "role": "accessory",
                "muscle_group": "Triceps",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "2-LAMcpzODU",
                "description": "Cable pushdown for tricep isolation",
                "difficulty": "beginner"
            },
        ],
        "pull": [
            {
                "id": "lat_pulldown",
                "name": "Lat Pulldown",
                "category": "pull",
                "role": "primary",
                "muscle_group": "Lats, Biceps",
                "sets": 4,
                "reps": "10-12",
                "rest_seconds": 75,
                "video_id": "CAwf7n6Luuc",
                "description": "Wide-grip lat pulldown for back width",
                "difficulty": "beginner"
            },
            {
                "id": "barbell_row",
                "name": "Barbell Row",
                "category": "pull",
                "role": "primary",
                "muscle_group": "Back, Biceps, Rear Delts",
                "sets": 4,
                "reps": "8-10",
                "rest_seconds": 90,
                "video_id": "FWJR5Ve8bnQ",
                "description": "Bent-over barbell row for back thickness",
                "difficulty": "intermediate"
            },
            {
                "id": "seated_cable_row",
                "name": "Seated Cable Row",
                "category": "pull",
                "role": "primary",
                "muscle_group": "Mid Back, Biceps",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 75,
                "video_id": "GZbfZ033f74",
                "description": "Seated cable row for mid-back development",
                "difficulty": "beginner"
            },
            {
                "id": "face_pulls",
                "name": "Face Pulls",
                "category": "pull",
                "role": "accessory",
                "muscle_group": "Rear Delts, Rotator Cuff",
                "sets": 3,
                "reps": "15-20",
                "rest_seconds": 45,
                "video_id": "rep-qVOkqgk",
                "description": "Cable face pull for shoulder health",
                "difficulty": "beginner"
            },
            {
                "id": "bicep_curls",
                "name": "Barbell Bicep Curls",
                "category": "pull",
                "role": "accessory",
                "muscle_group": "Biceps",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 60,
                "video_id": "ykJmrZ5v0Oo",
                "description": "Standing barbell curl for bicep development",
                "difficulty": "beginner"
            },
        ],
        "legs": [
            {
                "id": "barbell_squat",
                "name": "Barbell Back Squat",
                "category": "legs",
                "role": "primary",
                "muscle_group": "Quads, Glutes, Hamstrings",
                "sets": 4,
                "reps": "8-10",
                "rest_seconds": 120,
                "video_id": "ultWZbUMPL8",
                "description": "Back squat - fundamental lower body compound",
                "difficulty": "intermediate"
            },
            {
                "id": "leg_press",
                "name": "Leg Press",
                "category": "legs",
                "role": "primary",
                "muscle_group": "Quads, Glutes",
                "sets": 4,
                "reps": "10-12",
                "rest_seconds": 90,
                "video_id": "IZxyjW7MPJQ",
                "description": "Machine leg press for quad development",
                "difficulty": "beginner"
            },
            {
                "id": "romanian_deadlift",
                "name": "Romanian Deadlift",
                "category": "legs",
                "role": "primary",
                "muscle_group": "Hamstrings, Glutes, Lower Back",
                "sets": 3,
                "reps": "10-12",
                "rest_seconds": 90,
                "video_id": "JCXUYuzwNrM",
                "description": "Hip-hinge movement for posterior chain",
                "difficulty": "intermediate"
            },
            {
                "id": "leg_extension",
                "name": "Leg Extension",
                "category": "legs",
                "role": "accessory",
                "muscle_group": "Quads",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "YyvSfVjQeL0",
                "description": "Machine quad isolation exercise",
                "difficulty": "beginner"
            },
            {
                "id": "leg_curl",
                "name": "Lying Leg Curl",
                "category": "legs",
                "role": "accessory",
                "muscle_group": "Hamstrings",
                "sets": 3,
                "reps": "12-15",
                "rest_seconds": 60,
                "video_id": "1Tq3QdYUuHs",
                "description": "Machine hamstring isolation exercise",
                "difficulty": "beginner"
            },
        ],
        "core": [
            {
                "id": "cable_crunches",
                "name": "Cable Crunches",
                "category": "core",
                "role": "primary",
                "muscle_group": "Rectus Abdominis",
                "sets": 3,
                "reps": "15-20",
                "rest_seconds": 45,
                "video_id": "AV5PmrJSdaI",
                "description": "Kneeling cable crunch for weighted ab work",
                "difficulty": "intermediate"
            },
            {
                "id": "hanging_leg_raises",
                "name": "Hanging Leg Raises",
                "category": "core",
                "role": "primary",
                "muscle_group": "Lower Abs, Hip Flexors",
                "sets": 3,
                "reps": "10-15",
                "rest_seconds": 60,
                "video_id": "hdng3Nm1x_E",
                "description": "Hanging from bar with leg raises",
                "difficulty": "advanced"
            },
            {
                "id": "ab_wheel_rollout",
                "name": "Ab Wheel Rollout",
                "category": "core",
                "role": "primary",
                "muscle_group": "Core, Shoulders",
                "sets": 3,
                "reps": "8-12",
                "rest_seconds": 60,
                "video_id": "GXLQW0qvo8M",
                "description": "Anti-extension exercise for full core",
                "difficulty": "intermediate"
            },
            {
                "id": "russian_twist",
                "name": "Russian Twist",
                "category": "core",
                "role": "accessory",
                "muscle_group": "Obliques",
                "sets": 3,
                "reps": "15 each side",
                "rest_seconds": 45,
                "video_id": "wkD8rjkodUI",
                "description": "Seated rotation with optional weight",
                "difficulty": "beginner"
            },
            {
                "id": "weighted_plank",
                "name": "Weighted Plank",
                "category": "core",
                "role": "accessory",
                "muscle_group": "Core, Shoulders",
                "sets": 3,
                "reps": "30-45 sec",
                "rest_seconds": 45,
                "video_id": "ASdvN_XEl_c",
                "description": "Front plank with added weight on back",
                "difficulty": "intermediate"
            },
        ],
        "conditioning": [
            {
                "id": "battle_ropes",
                "name": "Battle Ropes",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Full Body, Cardio",
                "sets": 4,
                "reps": "30 sec",
                "rest_seconds": 30,
                "video_id": "he3cHao4gE0",
                "description": "Alternating wave pattern with heavy ropes",
                "difficulty": "intermediate"
            },
            {
                "id": "box_jumps",
                "name": "Box Jumps",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Legs, Explosive Power",
                "sets": 3,
                "reps": "8-10",
                "rest_seconds": 60,
                "video_id": "52r_Ul5k03g",
                "description": "Plyometric jump onto elevated box",
                "difficulty": "intermediate"
            },
            {
                "id": "rowing_machine",
                "name": "Rowing Machine",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Full Body, Cardio",
                "sets": 1,
                "reps": "5-10 min",
                "rest_seconds": 0,
                "video_id": "Q5_KFjbJb60",
                "description": "Cardio rowing for endurance",
                "difficulty": "beginner"
            },
            {
                "id": "kettlebell_swings",
                "name": "Kettlebell Swings",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Posterior Chain, Cardio",
                "sets": 3,
                "reps": "15-20",
                "rest_seconds": 45,
                "video_id": "YSxHifyI6s8",
                "description": "Hip-hinge explosive kettlebell movement",
                "difficulty": "intermediate"
            },
            {
                "id": "pull_ups",
                "name": "Pull-Ups",
                "category": "conditioning",
                "role": "primary",
                "muscle_group": "Lats, Biceps, Core",
                "sets": 3,
                "reps": "6-10",
                "rest_seconds": 90,
                "video_id": "eGo4IYlbE5g",
                "description": "Overhand grip pull-up for upper body",
                "difficulty": "advanced"
            },
        ],
    },
}


def get_exercises(equipment, category=None, role=None, difficulty=None):
    """Retrieve exercises filtered by equipment, category, role, and difficulty."""
    pool = EXERCISES.get(equipment, {})
    results = []
    categories = [category] if category else pool.keys()
    for cat in categories:
        exercises = pool.get(cat, [])
        for ex in exercises:
            if role and ex["role"] != role:
                continue
            if difficulty and ex["difficulty"] != difficulty:
                continue
            results.append(ex)
    return results
